
# dataparsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'OR ID EQ DATAdata : DATA ID EQ vlistvlist   : vlist OR v \n               | vv :   ID vsvs : vs ID\n          | emptyempty :'
    
_lr_action_items = {'DATA':([0,],[2,]),'$end':([1,5,6,7,8,9,11,12,],[0,-7,-1,-3,-4,-6,-5,-2,]),'ID':([2,4,5,8,9,10,11,],[3,5,-7,11,-6,5,-5,]),'EQ':([3,],[4,]),'OR':([5,6,7,8,9,11,12,],[-7,10,-3,-4,-6,-5,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'data':([0,],[1,]),'vlist':([4,],[6,]),'v':([4,10,],[7,12,]),'vs':([5,],[8,]),'empty':([5,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> data","S'",1,None,None,None),
  ('data -> DATA ID EQ vlist','data',4,'p_data','pdata.py',54),
  ('vlist -> vlist OR v','vlist',3,'p_vlist','pdata.py',58),
  ('vlist -> v','vlist',1,'p_vlist','pdata.py',59),
  ('v -> ID vs','v',2,'p_v','pdata.py',67),
  ('vs -> vs ID','vs',2,'p_vs','pdata.py',71),
  ('vs -> empty','vs',1,'p_vs','pdata.py',72),
  ('empty -> <empty>','empty',0,'p_empty','pdata.py',80),
]
